name: Build Skill
on:
  pull_request:
  workflow_dispatch:

jobs:
  py_build_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: pronovic/setup-poetry@v1
        with:
          version: 1.7.0
          cache-venv: true
          cache-poetry: true
      - name: Check build
        run: |
          poetry install --no-dev
          poetry build
      - name: PIP Audit
        uses: pypa/gh-action-pip-audit@v1.0.7
        with:
          # Upstream issues we can't really resolve from here
          ignore-vulns: "GHSA-r9hx-vwmv-q579 PYSEC-2022-43012 PYSEC-2023-228 PYSEC-2023-74 GHSA-9wx4-h78v-vm56"
