name: Update skill.json
on:
  push:
permissions:
  contents: write

jobs:
  update_skill_json:
    runs-on: ubuntu-latest
    steps:
      - name: Get Updated skill.json
        run: |
          python .github/workflows/scripts/update_skill_json.py action/skill
      - name: Push skill.json Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update skill.json
          repository: action/skill/
